

# Data Manipulation - Filters

## Learnings:

- rename columns in a DataFrame
- manipulate columns in a DataFrame (select, reorder, delete)
- filter dataframe
- assign to a column based on a condition

In [42]:
import pandas as pd

data = pd.read_csv('data/vehicles.csv')
data.head(2)
                   

Make              Model  Year  Engine Displacement  Cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   
1  AM General   FJ8c Post Office  1984                  4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

In [2]:
data.shape

(35952, 15)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Make                     35952 non-null  object 
 1   Model                    35952 non-null  object 
 2   Year                     35952 non-null  int64  
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object 
 6   Drivetrain               35952 non-null  object 
 7   Vehicle Class            35952 non-null  object 
 8   Fuel Type                35952 non-null  object 
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64  
 11  Highway MPG              35952 non-null  int64  
 12  Combined MPG             35952 non-null  int64  
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year        

## Checking the dataframe column names

Rename all columns at once:
- `data.columns` is an **attribute** of the DataFrame which results in a list-like of the column names
    - You can substitute it by another list containing the names you want 
    - Note you have to substitute the whole set of column names at once
    
- `data.rename()` is a **method** of a DataFrame, in which you can rename one column at once
    - You just need to pass a dictionary containing {'old_name':'new_name'} 
    - By default, it changes names of a **index** (`axis=0`), you can specify `axis=1` to change **column** names
    - the `inplace` argument

In [4]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

### Substituting `.columns` attribute

In [ ]:
# say for example we want to convert all columns to lowercase!

In [5]:
data.columns = ['make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year']

In [6]:
data.head()

make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [7]:
data.columns = ['make', 'model', 'Year', 'Engine Displacement', 'Cylinders',
               'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
               'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
               'CO2 Emission Grams/Mile', 'Fuel Cost/Year']

In [9]:
for col in data.columns:
    print(col)

Make
Model
Year
Engine Displacement
Cylinders
Transmission
Drivetrain
Vehicle Class
Fuel Type
Fuel Barrels/Year
City MPG
Highway MPG
Combined MPG
CO2 Emission Grams/Mile
Fuel Cost/Year


In [10]:
colnames = []
for col in data.columns:
    colnames.append(col.lower())

In [14]:
[col.lower().replace(' ','_').replace('/','_') for col in data.columns]

['make',
 'model',
 'year',
 'engine_displacement',
 'cylinders',
 'transmission',
 'drivetrain',
 'vehicle_class',
 'fuel_type',
 'fuel_barrels_year',
 'city_mpg',
 'highway_mpg',
 'combined_mpg',
 'co2_emission_grams_mile',
 'fuel_cost_year']

In [12]:
data.columns = [col.lower().replace(' ','_').replace('/','_') for col in data.columns]

In [13]:
data.head()

make                model  year  engine_displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   cylinders     transmission        drivetrain                vehicle_class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [15]:
data.columns = ['manufacturer']

ValueError: Length mismatch: Expected axis has 15 elements, new values have 1 elements

### `.rename() method`

`.rename({'old_column':'new_column'})`

#### returning a new dataframe

In [16]:
data.head(1)

make              model  year  engine_displacement  cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   

      transmission     drivetrain                vehicle_class fuel_type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0          19.388824        18           17            17   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950

In [23]:
data.rename({'make': 'manufacturer'}, axis=1)

manufacturer                model  year  engine_displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       cylinders     transmission        drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     vehicle_class fuel_type  fuel_barrels_year  city_mpg  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       highway_mpg  combined_mpg  co2_emission_grams_mile  fuel_cost_year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [24]:
data.rename(columns={'make': 'manufacturer', 'year':'model_year'})

manufacturer                model  model_year  engine_displacement  \
0            AM General    DJ Po Vehicle 2WD        1984                  2.5   
1            AM General     FJ8c Post Office        1984                  4.2   
2            AM General  Post Office DJ5 2WD        1985                  2.5   
3            AM General  Post Office DJ8 2WD        1985                  4.2   
4      ASC Incorporated                  GNX        1987                  3.8   
...                 ...                  ...         ...                  ...   
35947             smart         fortwo coupe        2013                  1.0   
35948             smart         fortwo coupe        2014                  1.0   
35949             smart         fortwo coupe        2015                  1.0   
35950             smart         fortwo coupe        2016                  0.9   
35951             smart         fortwo coupe        2016                  0.9   

       cylinders     transmission        drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     vehicle_class fuel_type  fuel_barrels_year  city_mpg  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       highway_mpg  combined_mpg  co2_emission_grams_mile  fuel_cost_year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [25]:
data = data.rename(columns={'make': 'manufacturer', 'year':'model_year'})

In [26]:
data.head()

manufacturer                model  model_year  engine_displacement  \
0        AM General    DJ Po Vehicle 2WD        1984                  2.5   
1        AM General     FJ8c Post Office        1984                  4.2   
2        AM General  Post Office DJ5 2WD        1985                  2.5   
3        AM General  Post Office DJ8 2WD        1985                  4.2   
4  ASC Incorporated                  GNX        1987                  3.8   

   cylinders     transmission        drivetrain                vehicle_class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

#### inplace

In [28]:
data.rename({'engine_displacement': 'engine_displacement2',
             'vehicle_class': 'vehicle_class2'}, axis=1, inplace=True)

In [29]:
# dataframe already changed
data.head()

manufacturer                model  model_year  engine_displacement2  \
0        AM General    DJ Po Vehicle 2WD        1984                   2.5   
1        AM General     FJ8c Post Office        1984                   4.2   
2        AM General  Post Office DJ5 2WD        1985                   2.5   
3        AM General  Post Office DJ8 2WD        1985                   4.2   
4  ASC Incorporated                  GNX        1987                   3.8   

   cylinders     transmission        drivetrain               vehicle_class2  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

If you try to assign an `inplace=True` command, check what happens:

In [30]:
data.rename({'year3': 'year10'}, axis=1)

manufacturer                model  model_year  \
0            AM General    DJ Po Vehicle 2WD        1984   
1            AM General     FJ8c Post Office        1984   
2            AM General  Post Office DJ5 2WD        1985   
3            AM General  Post Office DJ8 2WD        1985   
4      ASC Incorporated                  GNX        1987   
...                 ...                  ...         ...   
35947             smart         fortwo coupe        2013   
35948             smart         fortwo coupe        2014   
35949             smart         fortwo coupe        2015   
35950             smart         fortwo coupe        2016   
35951             smart         fortwo coupe        2016   

       engine_displacement2  cylinders     transmission        drivetrain  \
0                       2.5        4.0  Automatic 3-spd     2-Wheel Drive   
1                       4.2        6.0  Automatic 3-spd     2-Wheel Drive   
2                       2.5        4.0  Automatic 3-spd  Rear-Wheel Drive   
3                       4.2        6.0  Automatic 3-spd  Rear-Wheel Drive   
4                       3.8        6.0  Automatic 4-spd  Rear-Wheel Drive   
...                     ...        ...              ...               ...   
35947                   1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35948                   1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35949                   1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35950                   0.9        3.0        Auto(AM6)  Rear-Wheel Drive   
35951                   0.9        3.0     Manual 5-spd  Rear-Wheel Drive   

                    vehicle_class2 fuel_type  fuel_barrels_year  city_mpg  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       highway_mpg  combined_mpg  co2_emission_grams_mile  fuel_cost_year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [34]:
y = data.rename({'year': 'year3'}, axis=1, inplace=True)

In [32]:
data.head()

manufacturer                model  model_year  engine_displacement2  \
0        AM General    DJ Po Vehicle 2WD        1984                   2.5   
1        AM General     FJ8c Post Office        1984                   4.2   
2        AM General  Post Office DJ5 2WD        1985                   2.5   
3        AM General  Post Office DJ8 2WD        1985                   4.2   
4  ASC Incorporated                  GNX        1987                   3.8   

   cylinders     transmission        drivetrain               vehicle_class2  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [35]:
print(y)

None


Two options:
> 1. store it again on the variable `data`: 

    data = data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'})
> 2. Use the inplace argument `inplace =  True` to change the values within the dataframe automatically

    data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'}, inplace=True)
    

In [ ]:
# You can also assign to a different variable, of course
renamed_data = data.rename(columns={'make':'Manufacturer', 'year3':'ANO'})

In [ ]:
renamed_data.head(2)

In [ ]:
data.head(2)

## Reordering columns in a dataframe

>    - Remember you always pass a list of columns to access a dataframe

Just select the columns in a different order and overwrite the previous dataframe

In [36]:
data.head()

manufacturer                model  model_year  engine_displacement2  \
0        AM General    DJ Po Vehicle 2WD        1984                   2.5   
1        AM General     FJ8c Post Office        1984                   4.2   
2        AM General  Post Office DJ5 2WD        1985                   2.5   
3        AM General  Post Office DJ8 2WD        1985                   4.2   
4  ASC Incorporated                  GNX        1987                   3.8   

   cylinders     transmission        drivetrain               vehicle_class2  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [38]:
data[['manufacturer','model']]

manufacturer                model
0            AM General    DJ Po Vehicle 2WD
1            AM General     FJ8c Post Office
2            AM General  Post Office DJ5 2WD
3            AM General  Post Office DJ8 2WD
4      ASC Incorporated                  GNX
...                 ...                  ...
35947             smart         fortwo coupe
35948             smart         fortwo coupe
35949             smart         fortwo coupe
35950             smart         fortwo coupe
35951             smart         fortwo coupe

[35952 rows x 2 columns]

In [39]:
data[['model', 'manufacturer']]

model      manufacturer
0        DJ Po Vehicle 2WD        AM General
1         FJ8c Post Office        AM General
2      Post Office DJ5 2WD        AM General
3      Post Office DJ8 2WD        AM General
4                      GNX  ASC Incorporated
...                    ...               ...
35947         fortwo coupe             smart
35948         fortwo coupe             smart
35949         fortwo coupe             smart
35950         fortwo coupe             smart
35951         fortwo coupe             smart

[35952 rows x 2 columns]

In [43]:
data = pd.read_csv('data/vehicles.csv')

In [45]:
data.columns = [col.lower().replace(' ','_').replace('/','_') for col in data.columns]

In [47]:
data.columns

Index(['make', 'model', 'year', 'engine_displacement', 'cylinders',
       'transmission', 'drivetrain', 'vehicle_class', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'highway_mpg', 'combined_mpg',
       'co2_emission_grams_mile', 'fuel_cost_year'],
      dtype='object')

In [51]:
data[['fuel_cost_year', 'highway_mpg','make', 'model', 'year', 'engine_displacement', 'cylinders',
       'transmission', 'drivetrain', 'vehicle_class', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'combined_mpg',
       'co2_emission_grams_mile']]

fuel_cost_year  highway_mpg              make                model  \
0                1950           17        AM General    DJ Po Vehicle 2WD   
1                2550           13        AM General     FJ8c Post Office   
2                2100           17        AM General  Post Office DJ5 2WD   
3                2550           13        AM General  Post Office DJ8 2WD   
4                2550           21  ASC Incorporated                  GNX   
...               ...          ...               ...                  ...   
35947            1100           38             smart         fortwo coupe   
35948            1100           38             smart         fortwo coupe   
35949            1100           38             smart         fortwo coupe   
35950            1100           39             smart         fortwo coupe   
35951            1150           39             smart         fortwo coupe   

       year  engine_displacement  cylinders     transmission  \
0      1984                  2.5        4.0  Automatic 3-spd   
1      1984                  4.2        6.0  Automatic 3-spd   
2      1985                  2.5        4.0  Automatic 3-spd   
3      1985                  4.2        6.0  Automatic 3-spd   
4      1987                  3.8        6.0  Automatic 4-spd   
...     ...                  ...        ...              ...   
35947  2013                  1.0        3.0        Auto(AM5)   
35948  2014                  1.0        3.0        Auto(AM5)   
35949  2015                  1.0        3.0        Auto(AM5)   
35950  2016                  0.9        3.0        Auto(AM6)   
35951  2016                  0.9        3.0     Manual 5-spd   

             drivetrain                vehicle_class fuel_type  \
0         2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1         2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
2      Rear-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
3      Rear-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
4      Rear-Wheel Drive                 Midsize Cars   Premium   
...                 ...                          ...       ...   
35947  Rear-Wheel Drive                  Two Seaters   Premium   
35948  Rear-Wheel Drive                  Two Seaters   Premium   
35949  Rear-Wheel Drive                  Two Seaters   Premium   
35950  Rear-Wheel Drive                  Two Seaters   Premium   
35951  Rear-Wheel Drive                  Two Seaters   Premium   

       fuel_barrels_year  city_mpg  combined_mpg  co2_emission_grams_mile  
0              19.388824        18            17               522.764706  
1              25.354615        13            13               683.615385  
2              20.600625        16            16               555.437500  
3              25.354615        13            13               683.615385  
4              20.600625        14            16               555.437500  
...                  ...       ...           ...                      ...  
35947           9.155833        34            36               244.000000  
35948           9.155833        34            36               243.000000  
35949           9.155833        34            36               244.000000  
35950           9.155833        34            36               246.000000  
35951           9.417429        32            35               255.000000  

[35952 rows x 15 columns]

In [49]:
data

fuel_cost_year              make                model  year  \
0                1950        AM General    DJ Po Vehicle 2WD  1984   
1                2550        AM General     FJ8c Post Office  1984   
2                2100        AM General  Post Office DJ5 2WD  1985   
3                2550        AM General  Post Office DJ8 2WD  1985   
4                2550  ASC Incorporated                  GNX  1987   
...               ...               ...                  ...   ...   
35947            1100             smart         fortwo coupe  2013   
35948            1100             smart         fortwo coupe  2014   
35949            1100             smart         fortwo coupe  2015   
35950            1100             smart         fortwo coupe  2016   
35951            1150             smart         fortwo coupe  2016   

       engine_displacement  cylinders     transmission        drivetrain  \
0                      2.5        4.0  Automatic 3-spd     2-Wheel Drive   
1                      4.2        6.0  Automatic 3-spd     2-Wheel Drive   
2                      2.5        4.0  Automatic 3-spd  Rear-Wheel Drive   
3                      4.2        6.0  Automatic 3-spd  Rear-Wheel Drive   
4                      3.8        6.0  Automatic 4-spd  Rear-Wheel Drive   
...                    ...        ...              ...               ...   
35947                  1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35948                  1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35949                  1.0        3.0        Auto(AM5)  Rear-Wheel Drive   
35950                  0.9        3.0        Auto(AM6)  Rear-Wheel Drive   
35951                  0.9        3.0     Manual 5-spd  Rear-Wheel Drive   

                     vehicle_class fuel_type  fuel_barrels_year  city_mpg  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       highway_mpg  combined_mpg  co2_emission_grams_mile  
0               17            17               522.764706  
1               13            13               683.615385  
2               17            16               555.437500  
3               13            13               683.615385  
4               21            16               555.437500  
...            ...           ...                      ...  
35947           38            36               244.000000  
35948           38            36               243.000000  
35949           38            36               244.000000  
35950           39            36               246.000000  
35951           39            35               255.000000  

[35952 rows x 15 columns]

In [54]:
data[['model','make']]

model              make
0        DJ Po Vehicle 2WD        AM General
1         FJ8c Post Office        AM General
2      Post Office DJ5 2WD        AM General
3      Post Office DJ8 2WD        AM General
4                      GNX  ASC Incorporated
...                    ...               ...
35947         fortwo coupe             smart
35948         fortwo coupe             smart
35949         fortwo coupe             smart
35950         fortwo coupe             smart
35951         fortwo coupe             smart

[35952 rows x 2 columns]

In [53]:
data.loc[:, ['model','make']] # WRONG - not a list, you passed a string, string - not a list.

model              make
0        DJ Po Vehicle 2WD        AM General
1         FJ8c Post Office        AM General
2      Post Office DJ5 2WD        AM General
3      Post Office DJ8 2WD        AM General
4                      GNX  ASC Incorporated
...                    ...               ...
35947         fortwo coupe             smart
35948         fortwo coupe             smart
35949         fortwo coupe             smart
35950         fortwo coupe             smart
35951         fortwo coupe             smart

[35952 rows x 2 columns]

How can I get the `fuel cost/year` variable and put it at the beginning of the dataframe

In [55]:
data.columns

Index(['fuel_cost_year', 'make', 'model', 'year', 'engine_displacement',
       'cylinders', 'transmission', 'drivetrain', 'vehicle_class', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'highway_mpg', 'combined_mpg',
       'co2_emission_grams_mile'],
      dtype='object')

In [56]:
column_order = ['co2_emission_grams_mile','fuel_cost_year', 'make', 'model', 'year', 'engine_displacement',
       'cylinders', 'transmission', 'drivetrain', 'vehicle_class', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'highway_mpg', 'combined_mpg']

data = data.loc[:, column_order]

In [57]:
data

co2_emission_grams_mile  fuel_cost_year              make  \
0                   522.764706            1950        AM General   
1                   683.615385            2550        AM General   
2                   555.437500            2100        AM General   
3                   683.615385            2550        AM General   
4                   555.437500            2550  ASC Incorporated   
...                        ...             ...               ...   
35947               244.000000            1100             smart   
35948               243.000000            1100             smart   
35949               244.000000            1100             smart   
35950               246.000000            1100             smart   
35951               255.000000            1150             smart   

                     model  year  engine_displacement  cylinders  \
0        DJ Po Vehicle 2WD  1984                  2.5        4.0   
1         FJ8c Post Office  1984                  4.2        6.0   
2      Post Office DJ5 2WD  1985                  2.5        4.0   
3      Post Office DJ8 2WD  1985                  4.2        6.0   
4                      GNX  1987                  3.8        6.0   
...                    ...   ...                  ...        ...   
35947         fortwo coupe  2013                  1.0        3.0   
35948         fortwo coupe  2014                  1.0        3.0   
35949         fortwo coupe  2015                  1.0        3.0   
35950         fortwo coupe  2016                  0.9        3.0   
35951         fortwo coupe  2016                  0.9        3.0   

          transmission        drivetrain                vehicle_class  \
0      Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1      Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2      Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3      Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4      Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   
...                ...               ...                          ...   
35947        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35948        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35949        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35950        Auto(AM6)  Rear-Wheel Drive                  Two Seaters   
35951     Manual 5-spd  Rear-Wheel Drive                  Two Seaters   

      fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  
0       Regular          19.388824        18           17            17  
1       Regular          25.354615        13           13            13  
2       Regular          20.600625        16           17            16  
3       Regular          25.354615        13           13            13  
4       Premium          20.600625        14           21            16  
...         ...                ...       ...          ...           ...  
35947   Premium           9.155833        34           38            36  
35948   Premium           9.155833        34           38            36  
35949   Premium           9.155833        34           38            36  
35950   Premium           9.155833        34           39            36  
35951   Premium           9.417429        32           39            35  

[35952 rows x 15 columns]

In [59]:
# problems you may handle

# auto-assign a subset of the dataframe
data = data['make']

0              AM General
1              AM General
2              AM General
3              AM General
4        ASC Incorporated
               ...       
35947               smart
35948               smart
35949               smart
35950               smart
35951               smart
Name: make, Length: 35952, dtype: object

In [ ]:
data.head(2)

In [72]:
data = pd.read_csv('data/vehicles.csv')

In [73]:
data

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [75]:
data.rename({'Year':'Model_Year'}, axis=1, inplace=True)

In [77]:
# assign an inplace=True command:
data = data.rename({'Year':'Model_Year'}, axis=1, inplace=True)

In [79]:
print(data)

None


In [71]:
data.head(2)

AttributeError: 'NoneType' object has no attribute 'head'

In [80]:
print(data)

None


## Remove column (or row)

- The `.drop()` method
- By default, `.drop()` drops a row given its index.

In [82]:
data = pd.read_csv('data/vehicles.csv')

In [83]:
data

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [84]:
data.drop('Year')

KeyError: "['Year'] not found in axis"

In [ ]:
data.drop('Year')

In [85]:
data.drop('Year', axis=1)

Make                Model  Engine Displacement  Cylinders  \
0            AM General    DJ Po Vehicle 2WD                  2.5        4.0   
1            AM General     FJ8c Post Office                  4.2        6.0   
2            AM General  Post Office DJ5 2WD                  2.5        4.0   
3            AM General  Post Office DJ8 2WD                  4.2        6.0   
4      ASC Incorporated                  GNX                  3.8        6.0   
...                 ...                  ...                  ...        ...   
35947             smart         fortwo coupe                  1.0        3.0   
35948             smart         fortwo coupe                  1.0        3.0   
35949             smart         fortwo coupe                  1.0        3.0   
35950             smart         fortwo coupe                  0.9        3.0   
35951             smart         fortwo coupe                  0.9        3.0   

          Transmission        Drivetrain                Vehicle Class  \
0      Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1      Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2      Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3      Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4      Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   
...                ...               ...                          ...   
35947        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35948        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35949        Auto(AM5)  Rear-Wheel Drive                  Two Seaters   
35950        Auto(AM6)  Rear-Wheel Drive                  Two Seaters   
35951     Manual 5-spd  Rear-Wheel Drive                  Two Seaters   

      Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0       Regular          19.388824        18           17            17   
1       Regular          25.354615        13           13            13   
2       Regular          20.600625        16           17            16   
3       Regular          25.354615        13           13            13   
4       Premium          20.600625        14           21            16   
...         ...                ...       ...          ...           ...   
35947   Premium           9.155833        34           38            36   
35948   Premium           9.155833        34           38            36   
35949   Premium           9.155833        34           38            36   
35950   Premium           9.155833        34           39            36   
35951   Premium           9.417429        32           39            35   

       CO2 Emission Grams/Mile  Fuel Cost/Year  
0                   522.764706            1950  
1                   683.615385            2550  
2                   555.437500            2100  
3                   683.615385            2550  
4                   555.437500            2550  
...                        ...             ...  
35947               244.000000            1100  
35948               243.000000            1100  
35949               244.000000            1100  
35950               246.000000            1100  
35951               255.000000            1150  

[35952 rows x 14 columns]

In [88]:
data.drop(1)

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
5                 Acura          2.2CL/3.0CL  1997                  2.2   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission         Drivetrain  \
0            4.0  Automatic 3-spd      2-Wheel Drive   
2            4.0  Automatic 3-spd   Rear-Wheel Drive   
3            6.0  Automatic 3-spd   Rear-Wheel Drive   
4            6.0  Automatic 4-spd   Rear-Wheel Drive   
5            4.0  Automatic 4-spd  Front-Wheel Drive   
...          ...              ...                ...   
35947        3.0        Auto(AM5)   Rear-Wheel Drive   
35948        3.0        Auto(AM5)   Rear-Wheel Drive   
35949        3.0        Auto(AM5)   Rear-Wheel Drive   
35950        3.0        Auto(AM6)   Rear-Wheel Drive   
35951        3.0     Manual 5-spd   Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
5                  Subcompact Cars   Regular          14.982273        20   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
5               26            22               403.954545            1500  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35951 rows x 15 columns]

In [94]:
data.drop(1).reset_index(drop=True)

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General  Post Office DJ5 2WD  1985                  2.5   
2            AM General  Post Office DJ8 2WD  1985                  4.2   
3      ASC Incorporated                  GNX  1987                  3.8   
4                 Acura          2.2CL/3.0CL  1997                  2.2   
...                 ...                  ...   ...                  ...   
35946             smart         fortwo coupe  2013                  1.0   
35947             smart         fortwo coupe  2014                  1.0   
35948             smart         fortwo coupe  2015                  1.0   
35949             smart         fortwo coupe  2016                  0.9   
35950             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission         Drivetrain  \
0            4.0  Automatic 3-spd      2-Wheel Drive   
1            4.0  Automatic 3-spd   Rear-Wheel Drive   
2            6.0  Automatic 3-spd   Rear-Wheel Drive   
3            6.0  Automatic 4-spd   Rear-Wheel Drive   
4            4.0  Automatic 4-spd  Front-Wheel Drive   
...          ...              ...                ...   
35946        3.0        Auto(AM5)   Rear-Wheel Drive   
35947        3.0        Auto(AM5)   Rear-Wheel Drive   
35948        3.0        Auto(AM5)   Rear-Wheel Drive   
35949        3.0        Auto(AM6)   Rear-Wheel Drive   
35950        3.0     Manual 5-spd   Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          20.600625        16   
2      Special Purpose Vehicle 2WD   Regular          25.354615        13   
3                     Midsize Cars   Premium          20.600625        14   
4                  Subcompact Cars   Regular          14.982273        20   
...                            ...       ...                ...       ...   
35946                  Two Seaters   Premium           9.155833        34   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               17            16               555.437500            2100  
2               13            13               683.615385            2550  
3               21            16               555.437500            2550  
4               26            22               403.954545            1500  
...            ...           ...                      ...             ...  
35946           38            36               244.000000            1100  
35947           38            36               243.000000            1100  
35948           38            36               244.000000            1100  
35949           39            36               246.000000            1100  
35950           39            35               255.000000            1150  

[35951 rows x 15 columns]

## Deep vs Shallow copy on pandas

In [95]:
data_bkp = data

In [96]:
data_bkp

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [97]:
data.rename({'Make':'manufacturer'}, axis=1, inplace=True)

In [98]:
data.head()

manufacturer                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [123]:
x=257
y=x
x+=1
print(x,y)

256 256


In [124]:
x is y

True

In [115]:
data_bkp is data

True

In [100]:
data_bkp.head(2)

manufacturer              Model  Year  Engine Displacement  Cylinders  \
0   AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   
1   AM General   FJ8c Post Office  1984                  4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

In [125]:
data_bkp = data.copy()

In [139]:
data = data.rename({'Model':'model'}, axis=1)

In [127]:
data.head(2)

manufacturer              model  Year  Engine Displacement  Cylinders  \
0   AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   
1   AM General   FJ8c Post Office  1984                  4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

In [128]:
data_bkp

manufacturer                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [133]:
data_bkp = data

In [134]:
data_bkp is data

True

In [135]:
data_bkp = data.copy()

In [136]:
data_bkp is data

False

In [140]:
data_bkp == data

manufacturer  model  Year  Engine Displacement  Cylinders  \
0              True   True  True                 True       True   
1              True   True  True                 True       True   
2              True   True  True                 True       True   
3              True   True  True                 True       True   
4              True   True  True                 True       True   
...             ...    ...   ...                  ...        ...   
35947          True   True  True                 True       True   
35948          True   True  True                 True       True   
35949          True   True  True                 True       True   
35950          True   True  True                 True       True   
35951          True   True  True                 True       True   

       Transmission  Drivetrain  Vehicle Class  Fuel Type  Fuel Barrels/Year  \
0              True        True           True       True               True   
1              True        True           True       True               True   
2              True        True           True       True               True   
3              True        True           True       True               True   
4              True        True           True       True               True   
...             ...         ...            ...        ...                ...   
35947          True        True           True       True               True   
35948          True        True           True       True               True   
35949          True        True           True       True               True   
35950          True        True           True       True               True   
35951          True        True           True       True               True   

       City MPG  Highway MPG  Combined MPG  CO2 Emission Grams/Mile  \
0          True         True          True                     True   
1          True         True          True                     True   
2          True         True          True                     True   
3          True         True          True                     True   
4          True         True          True                     True   
...         ...          ...           ...                      ...   
35947      True         True          True                     True   
35948      True         True          True                     True   
35949      True         True          True                     True   
35950      True         True          True                     True   
35951      True         True          True                     True   

       Fuel Cost/Year  
0                True  
1                True  
2                True  
3                True  
4                True  
...               ...  
35947            True  
35948            True  
35949            True  
35950            True  
35951            True  

[35952 rows x 15 columns]

# Filter records
>    - `mask` concept
>    - `.query()` method

This is really important for data wrangling.

In [142]:
data = pd.read_csv('data/vehicles.csv')

In [143]:
data.head(2)

Make              Model  Year  Engine Displacement  Cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   
1  AM General   FJ8c Post Office  1984                  4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

## Simple Example: Starting with a numpy array. How can I filter the values of a list?

In [144]:
import numpy as np

In [145]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [146]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
my_array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [148]:
my_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

The results of `my_array > 5` is what is called **a mask**. A result containing the `True` and `False` results of an operation. 

In [149]:
my_array[5:]

array([ 6,  7,  8,  9, 10])

In [154]:
my_array[ [False, False, False, False, False,  True,  True,  True,  True, True] ]

array([ 6,  7,  8,  9, 10])

In [ ]:
mask=[]
for i in range(len(my_array)):
    if i %2!=0: 
        mask.append(True)
    else:
        mask.append(False)

In [158]:
my_array[my_array>5]

array([ 6,  7,  8,  9, 10])

Masks can be used as an index to select data!

In [17]:
my_array[ [False, False, False, False, False,  True,  True,  True,  True, True] ]

array([ 6,  7,  8,  9, 10])

In [18]:
my_array[my_array > 5]

array([ 6,  7,  8,  9, 10])

After selecting, you can do anything with it, for example assigning it. This operation is called a `vectorial` operation. It is done all at once.

In [160]:
my_array[my_array > 5] = 1000

In [161]:
my_array

array([   1,    2,    3,    4,    5, 1000, 1000, 1000, 1000, 1000])

In [162]:
my_matrix = np.random.randint(0, 10, size=(5,5))
my_matrix

array([[2, 7, 7, 9, 0],
       [4, 1, 7, 1, 5],
       [7, 7, 5, 8, 9],
       [7, 0, 7, 9, 4],
       [1, 1, 9, 6, 4]])

In [163]:
my_matrix > 5

array([[False,  True,  True,  True, False],
       [False, False,  True, False, False],
       [ True,  True, False,  True,  True],
       [ True, False,  True,  True, False],
       [False, False,  True,  True, False]])

In [164]:
my_matrix[ my_matrix > 5 ] = -99999

In [165]:
my_matrix

array([[     2, -99999, -99999, -99999,      0],
       [     4,      1, -99999,      1,      5],
       [-99999, -99999,      5, -99999, -99999],
       [-99999,      0, -99999, -99999,      4],
       [     1,      1, -99999, -99999,      4]])

In [ ]:
my_array[ my_array > 5 ] = 10

In [166]:
my_array

3

You can also save the condition

In [167]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [168]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
condition = my_array > 5 
condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
my_array

In [170]:
my_array[ condition ]

array([ 6,  7,  8,  9, 10])

## Bitwise logical operators - Combining conditions

To make more than one condition together, you can use 
- `&` - analogous to `and`
- `|` - analogous to `or` 

For example, get all numbers from my_array that are greater than 3 and smaller than 8

Let's do it in steps:
- get values greater than 3

In [171]:
my_array[my_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

- get values smaller than 8

In [172]:
my_array[my_array < 8]

array([1, 2, 3, 4, 5, 6, 7])

- get values greater than 3 and smaller than 8

In [173]:
greater_than_3 = my_array > 3

In [174]:
smaller_than_8 = my_array < 8

In [175]:
greater_than_3 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [176]:
smaller_than_8 

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [179]:
(my_array > 3) & (my_array < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [180]:
# (my_array > 3) or (my_array < 8)
(my_array > 3) | (my_array < 8)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
(my_array > 3) & (my_array < 8)

In [183]:
greater_than_3 & smaller_than_8

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [184]:
my_array[(greater_than_3) & (smaller_than_8)]

array([4, 5, 6, 7])

In [187]:
my_array[(my_array > 3) & (my_array < 8)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Now in a dataframe

Let's find the rows in which the Cylinders values are exactly 6.

In [188]:
data

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [190]:
city_more_15 = data['City MPG']>15 

In [191]:
data[city_more_15]

Make                Model  Year  Engine Displacement  Cylinders  \
0      AM General    DJ Po Vehicle 2WD  1984                  2.5        4.0   
2      AM General  Post Office DJ5 2WD  1985                  2.5        4.0   
5           Acura          2.2CL/3.0CL  1997                  2.2        4.0   
6           Acura          2.2CL/3.0CL  1997                  2.2        4.0   
7           Acura          2.2CL/3.0CL  1997                  3.0        6.0   
...           ...                  ...   ...                  ...        ...   
35947       smart         fortwo coupe  2013                  1.0        3.0   
35948       smart         fortwo coupe  2014                  1.0        3.0   
35949       smart         fortwo coupe  2015                  1.0        3.0   
35950       smart         fortwo coupe  2016                  0.9        3.0   
35951       smart         fortwo coupe  2016                  0.9        3.0   

          Transmission         Drivetrain                Vehicle Class  \
0      Automatic 3-spd      2-Wheel Drive  Special Purpose Vehicle 2WD   
2      Automatic 3-spd   Rear-Wheel Drive  Special Purpose Vehicle 2WD   
5      Automatic 4-spd  Front-Wheel Drive              Subcompact Cars   
6         Manual 5-spd  Front-Wheel Drive              Subcompact Cars   
7      Automatic 4-spd  Front-Wheel Drive              Subcompact Cars   
...                ...                ...                          ...   
35947        Auto(AM5)   Rear-Wheel Drive                  Two Seaters   
35948        Auto(AM5)   Rear-Wheel Drive                  Two Seaters   
35949        Auto(AM5)   Rear-Wheel Drive                  Two Seaters   
35950        Auto(AM6)   Rear-Wheel Drive                  Two Seaters   
35951     Manual 5-spd   Rear-Wheel Drive                  Two Seaters   

      Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0       Regular          19.388824        18           17            17   
2       Regular          20.600625        16           17            16   
5       Regular          14.982273        20           26            22   
6       Regular          13.733750        22           28            24   
7       Regular          16.480500        18           26            20   
...         ...                ...       ...          ...           ...   
35947   Premium           9.155833        34           38            36   
35948   Premium           9.155833        34           38            36   
35949   Premium           9.155833        34           38            36   
35950   Premium           9.155833        34           39            36   
35951   Premium           9.417429        32           39            35   

       CO2 Emission Grams/Mile  Fuel Cost/Year  
0                   522.764706            1950  
2                   555.437500            2100  
5                   403.954545            1500  
6                   370.291667            1400  
7                   444.350000            1650  
...                        ...             ...  
35947               244.000000            1100  
35948               243.000000            1100  
35949               244.000000            1100  
35950               246.000000            1100  
35951               255.000000            1150  

[23322 rows x 15 columns]

In [192]:
data['Cylinders'] == 4

0         True
1        False
2         True
3        False
4        False
         ...  
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Cylinders, Length: 35952, dtype: bool

In [ ]:
data['Cylinders'] == 4

In [193]:
data[data['Cylinders'] == 4]

Make                Model  Year  Engine Displacement  Cylinders  \
0      AM General    DJ Po Vehicle 2WD  1984                  2.5        4.0   
2      AM General  Post Office DJ5 2WD  1985                  2.5        4.0   
5           Acura          2.2CL/3.0CL  1997                  2.2        4.0   
6           Acura          2.2CL/3.0CL  1997                  2.2        4.0   
8           Acura          2.3CL/3.0CL  1998                  2.3        4.0   
...           ...                  ...   ...                  ...        ...   
35927        Yugo    GV Plus/GV/Cabrio  1990                  1.3        4.0   
35928        Yugo               GV/GVX  1987                  1.1        4.0   
35929        Yugo               GV/GVX  1989                  1.1        4.0   
35930        Yugo               GV/GVX  1989                  1.3        4.0   
35931        Yugo          Gy/yugo GVX  1986                  1.1        4.0   

          Transmission         Drivetrain                Vehicle Class  \
0      Automatic 3-spd      2-Wheel Drive  Special Purpose Vehicle 2WD   
2      Automatic 3-spd   Rear-Wheel Drive  Special Purpose Vehicle 2WD   
5      Automatic 4-spd  Front-Wheel Drive              Subcompact Cars   
6         Manual 5-spd  Front-Wheel Drive              Subcompact Cars   
8      Automatic 4-spd  Front-Wheel Drive              Subcompact Cars   
...                ...                ...                          ...   
35927     Manual 5-spd  Front-Wheel Drive              Subcompact Cars   
35928     Manual 4-spd  Front-Wheel Drive              Subcompact Cars   
35929     Manual 4-spd  Front-Wheel Drive              Subcompact Cars   
35930     Manual 5-spd  Front-Wheel Drive              Subcompact Cars   
35931     Manual 4-spd  Front-Wheel Drive             Minicompact Cars   

      Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0       Regular          19.388824        18           17            17   
2       Regular          20.600625        16           17            16   
5       Regular          14.982273        20           26            22   
6       Regular          13.733750        22           28            24   
8       Regular          14.982273        19           27            22   
...         ...                ...       ...          ...           ...   
35927   Regular          13.184400        23           28            25   
35928   Regular          12.677308        24           29            26   
35929   Regular          12.677308        24           29            26   
35930   Regular          13.184400        23           28            25   
35931   Regular          13.184400        22           29            25   

       CO2 Emission Grams/Mile  Fuel Cost/Year  
0                   522.764706            1950  
2                   555.437500            2100  
5                   403.954545            1500  
6                   370.291667            1400  
8                   403.954545            1500  
...                        ...             ...  
35927               355.480000            1350  
35928               341.807692            1300  
35929               341.807692            1300  
35930               355.480000            1350  
35931               355.480000            1350  

[13494 rows x 15 columns]

In [194]:
data.loc[:, 'Cylinders']

0        4.0
1        6.0
2        4.0
3        6.0
4        6.0
        ... 
35947    3.0
35948    3.0
35949    3.0
35950    3.0
35951    3.0
Name: Cylinders, Length: 35952, dtype: float64

In [199]:
[col.startswith('Fuel') for col in data.columns]

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True]

In [198]:
data.loc[data['Cylinders'] == 4, [col.startswith('Fuel') for col in data.columns]]

Fuel Type  Fuel Barrels/Year  Fuel Cost/Year
0       Regular          19.388824            1950
2       Regular          20.600625            2100
5       Regular          14.982273            1500
6       Regular          13.733750            1400
8       Regular          14.982273            1500
...         ...                ...             ...
35927   Regular          13.184400            1350
35928   Regular          12.677308            1300
35929   Regular          12.677308            1300
35930   Regular          13.184400            1350
35931   Regular          13.184400            1350

[13494 rows x 3 columns]

### Example

In [ ]:
# create a column with all zeroes named - 'fl_city_car'

data['fl_city_car'] = 0

In [200]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [ ]:
(data['City MPG']) > (data['Highway MPG'])

In [201]:
# assign 1 to 'fl_city_car' all cars that have 'City MPG' > 'Highway MPG'

data.loc[(data['City MPG']) > (data['Highway MPG']), 'fl_city_car'] = 1

In [202]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year', 'fl_city_car'],
      dtype='object')

In [208]:
data

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  \
0               17            17               522.764706            1950   
1               13            13               683.615385            2550   
2               17            16               555.437500            2100   
3               13            13               683.615385            2550   
4               21            16               555.437500            2550   
...            ...           ...                      ...             ...   
35947           38            36               244.000000            1100   
35948           38            36               243.000000            1100   
35949           38            36               244.000000            1100   
35950           39            36               246.000000            1100   
35951           39            35               255.000000            1150   

       fl_city_car  
0              1.0  
1              NaN  
2             10.0  
3              NaN  
4             10.0  
...            ...  
35947         10.0  
35948         10.0  
35949         10.0  
35950         10.0  
35951         10.0  

[35952 rows x 16 columns]

In [207]:
data.loc[(data['City MPG']) < (data['Highway MPG']), 'fl_city_car'] = 10

In [209]:
data.loc[(data['City MPG']) > (data['Highway MPG']), 'fl_city_car']

0        1.0
47       1.0
48       1.0
3069     1.0
3070     1.0
        ... 
33293    1.0
33294    1.0
33295    1.0
33374    1.0
33375    1.0
Name: fl_city_car, Length: 183, dtype: float64

## You can combine conditions

Cars from `Ford` and 6 `Cylinders`

In [ ]:
data.loc[:, :]

In [ ]:
data['std'] = data[['City MPG','Highway MPG','Combined MPG']].std(axis=1)

In [ ]:
data.loc[data['std'] != 0, :]

In [ ]:
data.loc[(data['Cylinders'] == 6) & (data['Make'] == 'Ford'), :]

In [ ]:
# careful with:

data.loc[data['Make']=='Ford' & data['Cylinders']==6, :] # WRONG!!

## You can put the conditions in variables as well

In [ ]:
condition1 = (data['Make']=='Ford')
condition2 = (data['Cylinders']==6)
condition3 = (data['Combined MPG'] < 18)

In [ ]:
data.loc[condition1 & condition2 & condition3, :]

## Another way to do the same thing.

* using the method `query`

The method `query` receives a string in which you can say your condition. Important things:
- `.query()` is a method of your dataframe
- `.query()` method receives a string 
- Every word inside the string that is not `quoted` is considered a variable of your dataframe (so, for example `.query('Year == 1999')` will look for the variable `Year`. Another example: if you try to run `.query('Make == Ford')` will look both for the column name `Make` and the column named `Ford`. If you want the results of the column `Make` to match the **string** Ford, you have to run `.query('Make == "Ford"')`
- If your column has spaces, you have to call it using backticks like in **.query('\`Engine Displacement\` < 4')**:

In [210]:
data.query('Make == "Ford"')

Make               Model  Year  Engine Displacement  Cylinders  \
11440  Ford        Aerostar Van  1986                  2.3        4.0   
11441  Ford        Aerostar Van  1986                  2.3        4.0   
11442  Ford        Aerostar Van  1986                  2.8        6.0   
11443  Ford        Aerostar Van  1986                  2.8        6.0   
11444  Ford        Aerostar Van  1986                  3.0        6.0   
...     ...                 ...   ...                  ...        ...   
14381  Ford  Windstar FWD Wagon  2000                  3.0        6.0   
14382  Ford  Windstar FWD Wagon  2000                  3.8        6.0   
14383  Ford  Windstar FWD Wagon  2001                  3.8        6.0   
14384  Ford  Windstar FWD Wagon  2002                  3.8        6.0   
14385  Ford  Windstar FWD Wagon  2003                  3.8        6.0   

          Transmission         Drivetrain  Vehicle Class Fuel Type  \
11440  Automatic 4-spd   Rear-Wheel Drive           Vans   Regular   
11441     Manual 5-spd   Rear-Wheel Drive           Vans   Regular   
11442  Automatic 4-spd   Rear-Wheel Drive           Vans   Regular   
11443     Manual 5-spd   Rear-Wheel Drive           Vans   Regular   
11444     Manual 5-spd   Rear-Wheel Drive           Vans   Regular   
...                ...                ...            ...       ...   
14381  Automatic 4-spd  Front-Wheel Drive  Minivan - 2WD   Regular   
14382  Automatic 4-spd  Front-Wheel Drive  Minivan - 2WD   Regular   
14383  Automatic 4-spd  Front-Wheel Drive  Minivan - 2WD   Regular   
14384  Automatic 4-spd  Front-Wheel Drive  Minivan - 2WD   Regular   
14385  Automatic 4-spd  Front-Wheel Drive  Minivan - 2WD   Regular   

       Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
11440          17.347895        18           22            19   
11441          13.733750        23           26            24   
11442          19.388824        15           21            17   
11443          18.311667        16           22            18   
11444          17.347895        17           22            19   
...                  ...       ...          ...           ...   
14381          19.388824        15           21            17   
14382          19.388824        15           21            17   
14383          18.311667        16           22            18   
14384          18.311667        16           21            18   
14385          18.311667        16           22            18   

       CO2 Emission Grams/Mile  Fuel Cost/Year  fl_city_car  
11440               467.736842            1750         10.0  
11441               370.291667            1400         10.0  
11442               522.764706            1950         10.0  
11443               493.722222            1850         10.0  
11444               467.736842            1750         10.0  
...                        ...             ...          ...  
14381               522.764706            1950         10.0  
14382               522.764706            1950         10.0  
14383               493.722222            1850         10.0  
14384               493.722222            1850         10.0  
14385               493.722222            1850         10.0  

[2946 rows x 16 columns]

In [ ]:
data.query('Cylinders == 4 and Make == "Ford"')

In [ ]:
data.query('`City MPG` > `Highway MPG`')

In [ ]:
data.query('Cylinders == 4')

In [ ]:
numero_cilindros = 6
data.query(f'Make == "Acura" and Cylinders == {numero_cilindros}')

In [ ]:
data.query('`City MPG` > `Highway MPG`')

In [ ]:
numero_cilindros = 4
data.query(f'Make == "Acura" and Cylinders == {numero_cilindros}')